# Generated by Django 4.0.1 on 2022-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('ID', models.UUIDField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Year', models.IntegerField(blank=True, null=True)),
                ('Author', models.CharField(blank=True, max_length=200, null=True)),
                ('Availability', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
