# Generated by Django 4.0.1 on 2022-01-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('Library_ID', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Street', models.CharField(max_length=200, null=True)),
                ('Building', models.IntegerField(blank=True, null=True)),
                ('Name_of_the_book', models.CharField(max_length=200, null=True)),
                ('Book_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Quantity_of_books', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
