# Generated by Django 4.0.1 on 2022-01-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_library_alter_book_author_alter_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('Student_ID', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Surname', models.CharField(max_length=200, null=True)),
                ('Book_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
