# Generated by Django 4.0.1 on 2022-01-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Surname', models.CharField(max_length=200, null=True)),
                ('Telephone_number', models.IntegerField(blank=True, null=True)),
                ('Borrowing_duration', models.IntegerField(blank=True, null=True)),
                ('Program_ID', models.IntegerField(blank=True)),
                ('Name_of_the_book', models.CharField(max_length=200)),
            ],
        ),
    ]
