# Generated by Django 4.0.1 on 2022-01-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_programs',
            fields=[
                ('Program_ID', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Duration_of_study', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('University_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Study_program', models.CharField(max_length=200, null=True)),
                ('Program_ID', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
